### ISSUE TITLE
Cloudformation throws UserPoolTestDomain ROLLBACK_FAILED

### ISSUE THREAD

**Issue by Pelirrojo** [rosberglinhares/CloudFormationCognitoCustomResources#6]
Hi there,
Thanks for the amazing Custom Resources!

I've been playing with it but I can't deploy:

Cloudformation event error:
````bash
13 Nov 2018 16:59:53 | UserPoolTestDomain | CREATE_FAILED | Invalid Response object: 'null' is not a valid ResponseStatus
-- | -- | -- | --
````

CloudWatch Errors:
````javascript
2018-11-13T16:37:14.250Z	5ec5c2ab-e762-11e8-9a5d-d7e6fe71fea6	CognitoUserPoolDomain Error for request type Create: { InternalErrorException: Internal server error again.
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'Internal server error again.',
code: 'InternalErrorException',
time: 2018-11-13T16:37:14.249Z,
requestId: '6028fc4b-e762-11e8-a08b-ffae2b14856f',
statusCode: 500,
retryable: true }
````

I've try to deploy in two cloudformation templates (one for lambdas & permission and another for demo resources) but the same problem there.

**Do you have experiment the same problem?**

Thanks,
Manuel

**Comment by aklas** [comment]
Yup. I am having the same issue. Where you able to resolve it?

**Comment by Pelirrojo** [comment]
No, finally we use an cli command scripted to do the trick.

**Comment by aklas** [comment]
I figured it out. You have to specify a unique domain:

`UserPoolTestDomain:`
`    Type: 'Custom::CognitoUserPoolDomain`
`    Properties:`
`      ServiceToken: !GetAtt CloudFormationCognitoUserPoolDomain.Arn`
`      UserPoolId: !Ref UserPoolTest`
`      Domain: <unique domain that hasn't already been taken>` **<--#Here**
Thanks
:)
